### ISSUE TITLE
Include a license for the serde-rs book

### ISSUE THREAD

**Issue by jamesmunns** [serde-rs/serde-rs.github.io#139]
Hey all,

I'm working on publishing a wire format specification for [postcard](https://docs.rs/postcard) v1.0, and I plan to cite the Serde book (specifically the serde data model chapter) as part of my specification.

I don't see a license anywhere, so I wanted to check in about this.

I plan to use [`CC-BY-SA 4.0`](https://creativecommons.org/licenses/by-sa/4.0/), would you be open to a PR adding this license to the book (or another, like [`CC0`](https://creativecommons.org/share-your-work/public-domain/cc0/)) to the repo?

Thanks!

**Comment by dtolnay** [comment]
CC-BY-SA 4.0 would be good. Could you please send a PR with an exact copy of the license file from https://github.com/dtolnay/rust-quiz?

**Comment by jamesmunns** [comment]
Thanks! Opened #140 to address.
