### ISSUE TITLE
`rename_all_fields` documentation is missing

### ISSUE THREAD

**Issue by omid** [serde-rs/serde-rs.github.io#161]
`rename_all_fields` attribute for containers documentation is missing.

**Comment by cj495840252** [comment]
rename_all is exactly the seem as rename_all_fields , maybe it's redundant

**Comment by omid** [comment]
Thanks for reminding me to check it again... now it's documented or published.
https://serde.rs/container-attrs.html

**Comment by omid** [comment]
Here is the commit: https://github.com/serde-rs/serde-rs.github.io/pull/162
