### ISSUE TITLE
Sidebar is missing if JavaScript is disabled

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde-rs.github.io#28]
Makes it seem like we have practically no documentation. Possibly mdBook would not have this problem (https://github.com/serde-rs/serde-rs.github.io/issues/17).

**Comment by kscz** [comment]
Even just calling out "Hey, our navigation system only works if you have javascript enabled!" would help make sure people like me don't get confused.

**Comment by dtolnay** [comment]
Fixed in 9d4719d891023d7493dbb88a03c87b7b02537818.

**Comment by dtolnay** [comment]
I reverted this to fix #30. Someone who understand javascript should take a look...

**Comment by dtolnay** [comment]
Fixed again, the right way I think.
