### ISSUE TITLE
Write a CONTRIBUTING.md

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde-rs.github.io#82]
Basically saying to only make content changes in the `_src` directory, the person merging the PR will deal with regenerating the HTML.

**Comment by dtolnay** [comment]
I don't have much to say, but added in https://github.com/serde-rs/serde-rs.github.io/commit/c202e251a805105b7d4c3c74ad17bf42b208964c.

**Comment by softprops** [comment]
that's for this. I know it sounds silly but its more straightforward for contributors to figure out what they need and what they don't :)
