### ISSUE TITLE
https access to serde.rs is not signed properly

### ISSUE THREAD

**Issue by oli-obk** [serde-rs/serde-rs.github.io#9]

**Comment by dtolnay** [comment]
I will give this a shot: https://blog.keanulee.com/2014/10/11/setting-up-ssl-on-github-pages.html

**Comment by dtolnay** [comment]
I think it worked. @oli-obk please confirm. There should be a redirect from http to https for both serde.rs and docs.serde.rs.

**Comment by oli-obk** [comment]
Works superb
